"""empty message

Revision ID: a7f988c03cb8
Revises: 087df430b59d
Create Date: 2018-07-15 16:51:36.232660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7f988c03cb8'
down_revision = '087df430b59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_timestamp', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
